api_conf = {
    'version': '1.0',
    'title': 'OAuth 2.0/OpenIDConnect 1.0 API',
    'description': "A OAuth2 auth server blueprint module for flask.",
    # 'terms_url': None,
    # 'license': None,
    # 'license_url': None,
    # 'contact': None,
    # 'contact_url': None,
    # 'contact_email': None,
    # 'authorizations': None,
    # 'security': None,
    # 'doc': "/docs/",
    # 'default_id': "oauth",
    # 'default': "Default",
    # 'default_label': "Default namespace",
    # 'validate': None,
    # 'tags': None,
    # 'prefix': '',
    # 'ordered': False,
    # 'default_mediatype': 'application/json',
    # 'decorators': [],
    # 'catch_all_404s': False,
    # 'serve_challenge_on_401': False,
    # 'format_checker': None
}
