api_conf = {
    'version': '1.0',
    'title': 'exTHmUI YellowPage API',
    'description': "A exthmui YellowPageData restful api blueprint module for flask.",
    'terms_url': None,
    'license': None,
    'license_url': None,
    'contact': None,
    'contact_url': None,
    'contact_email': None,
    'authorizations': None,
    'security': None,
    'doc': "/docs/",
    'default_id': None,
    'default': "default",
    'default_label': "Default namespace",
    'validate': None,
    'tags': None,
    'prefix': '',
    'ordered': False,
    'default_mediatype': 'application/json',
    'decorators': [],
    'catch_all_404s': False,
    'serve_challenge_on_401': False,
    'format_checker': None
}
